import type { AiAnswer, AutoReplyRule, Guild, MessageRecord, Schedule } from './types.js';
import { allMessages, clearMessages, searchMessages, upsertMessages } from './db.js';
import { ApiError, api, apiOrigin, askAi, createMemory, createRule, createSchedule, currentUser, deleteCloudData, deleteRule, deleteSchedule, exchangeLoginCode, getPublicConfig, listGuilds, listMemories, listRules, listSchedules, leaveOneGuild, logout, updateRule } from './api.js';
import { parseDiscordDataPackage } from './importer.js';

type User = { id: string; username: string; aiCredits: number; freeQuestionsRemaining: number; cloudEnabled: boolean };
type View = 'overview' | 'servers' | 'messages' | 'memory' | 'scheduler' | 'auto-reply' | 'settings';
let view: View = 'overview';
let user: User | undefined;
let guilds: Guild[] = [];
let messages: MessageRecord[] = [];
let schedules: Schedule[] = [];
let rules: AutoReplyRule[] = [];
let memories: Record<string, unknown>[] = [];
let notice = '';
const app = document.querySelector<HTMLDivElement>('#app')!;

const esc = (value: unknown): string => String(value ?? '').replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' }[char] || char));
const dateText = (value: unknown): string => { const date = new Date(String(value)); return Number.isNaN(date.getTime()) ? 'Unknown' : date.toLocaleString(); };
const errorText = (error: unknown): string => error instanceof ApiError || error instanceof Error ? error.message : 'Unexpected error';

async function boot(): Promise<void> {
  const code = new URLSearchParams(location.search).get('code');
  if (code) { try { await exchangeLoginCode(code); history.replaceState({}, '', location.pathname); } catch (error) { notice = errorText(error); } }
  try { user = (await currentUser()).user; await refresh(); } catch { user = undefined; }
  render();
}

async function refresh(): Promise<void> {
  messages = await searchMessages({}, 300);
  if (!user) return;
  try { guilds = (await listGuilds()).guilds; } catch (error) { notice = errorText(error); }
  try { schedules = (await listSchedules()).schedules; rules = (await listRules()).rules; memories = (await listMemories()).memories; } catch { /* optional cloud panels */ }
}

function nav(key: View, label: string): string { return '<button class="' + (view === key ? 'active' : '') + '" data-view="' + key + '">' + label + '</button>'; }
function pageTitle(): string { return ({ overview: 'Your Discord workspace', servers: 'Manage servers', messages: 'Your message history', memory: 'AI Memory', scheduler: 'Scheduled messages', 'auto-reply': 'Keyword auto-replies', settings: 'Privacy & Settings' } as Record<View, string>)[view]; }
function messageRows(rows: MessageRecord[]): string {
  if (!rows.length) return '<div class="empty">No messages match those filters.</div>';
  return '<div class="table-wrap"><table class="table"><thead><tr><th>When</th><th>Where</th><th>Message</th></tr></thead><tbody>' + rows.map((message) => '<tr><td>' + esc(dateText(message.timestamp)) + '</td><td>' + esc(message.guildName || 'Direct message') + '<br><span class="pill">#' + esc(message.channelName || message.channelId || 'unknown') + '</span></td><td class="message">' + esc(message.content) + (message.jumpUrl ? '<br><a class="link" target="_blank" href="' + esc(message.jumpUrl) + '">Open in Discord</a>' : '') + '</td></tr>').join('') + '</tbody></table></div>';
}
function render(): void {
  const content = view === 'overview' ? overview() : view === 'servers' ? servers() : view === 'messages' ? messagesPage() : view === 'memory' ? memoryPage() : view === 'scheduler' ? schedulerPage() : view === 'auto-reply' ? rulesPage() : settingsPage();
  app.innerHTML = '<div class="shell"><aside class="side"><div class="brand">Discord Memory</div><p class="tagline">Server cleanup and a private search engine for your Discord history.</p><nav class="nav">' + nav('overview', 'Overview') + nav('servers', 'Servers') + nav('messages', 'Messages') + nav('memory', 'AI Memory') + nav('scheduler', 'Scheduler') + nav('auto-reply', 'Auto Reply') + nav('settings', 'Privacy & Settings') + '</nav><div class="side-footer">Your data stays local until you explicitly import it to cloud storage.</div></aside><main class="content"><div class="top"><div><div class="eyebrow">Discord Server Leaver · V2</div><h1 class="title">' + pageTitle() + '</h1><p class="sub">' + (user ? 'Signed in as ' + esc(user.username) : 'Start with local history tools, then connect Discord when ready.') + '</p></div><div class="actions">' + (user ? '<span class="pill">' + user.freeQuestionsRemaining + ' free AI · ' + user.aiCredits + ' credits</span><button class="btn ghost" data-action="logout">Sign out</button>' : '<button class="btn primary" data-action="login">Connect Discord</button>') + '</div></div>' + (notice ? '<div class="notice">' + esc(notice) + ' <button class="btn ghost" data-action="dismiss">Dismiss</button></div>' : '') + content + '</main></div>';
  wire();
}
function overview(): string { return '<div class="grid"><div class="stat"><div class="label">Servers</div><div class="value">' + (guilds.length || '—') + '</div></div><div class="stat"><div class="label">Local messages</div><div class="value">' + messages.length + '</div></div><div class="stat"><div class="label">AI credits</div><div class="value">' + (user?.aiCredits || 0) + '</div></div><div class="stat"><div class="label">Memories</div><div class="value">' + memories.length + '</div></div></div><section class="card"><h2>Start here</h2><p>Import your official Discord Data Package to search your own messages by server, channel, phrase, and date.</p><div class="toolbar"><button class="btn primary" data-view="messages">Import history</button><button class="btn" data-view="servers">Clean up servers</button></div></section><section class="card"><h2>Compliant automation</h2><p>Scheduling and auto-replies are sent by an installed Discord bot with server approval. This tool does not automate a normal user account.</p></section>'; }
function servers(): string { return '<section class="card"><div class="row"><div><h2>Bulk leave</h2><p>Select servers to leave. Owned servers are protected.</p></div><button class="btn danger" data-action="leave">Leave selected</button></div><div class="toolbar"><input class="input" id="guild-filter" placeholder="Search servers"><button class="btn ghost" data-action="refresh">Refresh</button></div><div class="table-wrap"><table class="table"><thead><tr><th></th><th>Server</th><th>Members</th><th>Status</th></tr></thead><tbody>' + (guilds.length ? guilds.map((guild) => '<tr><td><input type="checkbox" data-guild="' + esc(guild.id) + '" ' + (guild.owner ? 'disabled' : '') + '></td><td><div class="server-cell">' + guildIcon(guild) + '<span>' + esc(guild.name) + '</span></div></td><td>' + (guild.approximate_member_count ?? '—') + '</td><td>' + (guild.owner ? '<span class="pill">Owner</span>' : '<span class="pill">Leaveable</span>') + '</td></tr>').join('') : '<tr><td colspan="4">Connect Discord and refresh to load servers.</td></tr>') + '</tbody></table></div></section>'; }
function guildIcon(guild: Guild): string { if (guild.icon) { const iconUrl = 'https://cdn.discordapp.com/icons/' + esc(guild.id) + '/' + esc(guild.icon) + (guild.icon.startsWith('a_') ? '.gif' : '.png') + '?size=64'; return '<img class="guild-icon" src="' + iconUrl + '" alt="">'; } return '<div class="guild-icon-placeholder"></div>'; }
function messagesPage(): string { return '<section class="card"><h2>Import your history</h2><p>Discord’s official Data Package contains messages you sent. Import stays local unless cloud memory is unlocked.</p><div class="toolbar"><input type="file" id="history-file" accept=".zip,.json,.csv"><button class="btn" data-action="clear-local">Delete local history</button><button class="btn" data-action="cloud-sync">Sync to cloud</button></div></section><section class="card"><h2>Search messages</h2><div class="toolbar"><input class="input" id="message-query" placeholder="Search exact words or phrases"><input class="input" id="message-from" type="date"><input class="input" id="message-to" type="date"><button class="btn primary" data-action="search">Search</button></div><div id="message-results">' + messageRows(messages) + '</div></section><section class="card"><h2>Ask your history</h2><p>Two questions are free. Answers cite the messages used.</p><div class="toolbar"><input class="input" id="ai-question" placeholder="Who was trying to farm with me?"><button class="btn primary" data-action="ask">Ask AI</button></div><div id="ai-answer"></div></section>'; }
function memoryPage(): string { return '<section class="card"><h2>Saved memories</h2><form id="memory-form" class="form-grid"><div class="field"><label>Title</label><input class="input" name="title" required></div><div class="field"><label>Tags</label><input class="input" name="tags"></div><div class="field full"><label>Memory</label><textarea name="content" required></textarea></div><button class="btn primary">Save memory</button></form></section><section class="card">' + (memories.length ? memories.map((memory) => '<div class="card"><strong>' + esc(memory.title) + '</strong><p>' + esc(memory.content) + '</p></div>').join('') : '<div class="empty">No saved memories yet.</div>') + '</section>'; }
function schedulerPage(): string { return '<section class="card"><h2>Schedule a bot message</h2><p>Requires an installed bot and Manage Server permission.</p><form id="schedule-form" class="form-grid"><div class="field"><label>Server ID</label><input class="input" name="guildId" required></div><div class="field"><label>Channel ID</label><input class="input" name="channelId" required></div><div class="field"><label>Send at</label><input class="input" type="datetime-local" name="runAt" required></div><div class="field"><label>Repeat</label><select class="select" name="recurrence"><option value="none">Once</option><option value="daily">Daily</option><option value="interval">Every 15 minutes</option></select></div><div class="field full"><label>Message</label><textarea name="content" required></textarea></div><button class="btn primary">Schedule</button></form></section><section class="card"><h2>Scheduled</h2>' + (schedules.length ? schedules.map((schedule) => '<div class="row"><span>' + esc(schedule.content) + '</span><button class="btn ghost" data-delete-schedule="' + esc(schedule.id) + '">Delete</button></div>').join('<hr>') : '<div class="empty">No scheduled messages.</div>') + '</section>'; }
function rulesPage(): string { return '<section class="card"><h2>Create a keyword rule</h2><p>Replies are bot messages with cooldown and hourly limits.</p><form id="rule-form" class="form-grid"><div class="field"><label>Server ID</label><input class="input" name="guildId" required></div><div class="field"><label>Channel ID</label><input class="input" name="channelId"></div><div class="field"><label>Keyword</label><input class="input" name="keyword" required></div><div class="field"><label>Match</label><select class="select" name="match"><option value="contains">Contains</option><option value="exact">Exact</option></select></div><div class="field full"><label>Reply</label><textarea name="response" required></textarea></div><button class="btn primary">Create rule</button></form></section><section class="card"><h2>Rules</h2>' + (rules.length ? rules.map((rule) => '<div class="row"><span><strong>' + esc(rule.keyword) + '</strong> → ' + esc(rule.response) + '</span><span><button class="btn ghost" data-toggle-rule="' + esc(rule.id) + '">Toggle</button><button class="btn ghost" data-delete-rule="' + esc(rule.id) + '">Delete</button></span></div>').join('<hr>') : '<div class="empty">No auto-reply rules.</div>') + '</section>'; }
function settingsPage(): string { return '<section class="card"><h2>Privacy & data</h2><p>Local history stays in this browser. Cloud data is account-scoped.</p><div class="toolbar"><button class="btn danger" data-action="delete-cloud">Delete cloud data</button><button class="btn danger" data-action="clear-local">Delete local history</button></div></section><section class="card"><h2>Support development</h2><p>Help keep this extension free and maintained!</p><div class="form-grid"><div class="field"><label>Custom amount (USD)</label><div class="donation-input-wrapper"><span class="currency-symbol">$</span><input class="input donation-input" id="custom-amount" type="number" min="1" max="500" step="1" placeholder="5.00"></div></div><div class="field"><button class="btn primary full-width" data-action="donate-custom">Donate Custom Amount</button></div></div><div class="quick-amounts"><button class="btn" data-action="donate-5">$5</button><button class="btn" data-action="donate-10">$10</button><button class="btn" data-action="donate-25">$25</button><button class="btn" data-action="donate-50">$50</button></div><div class="toolbar"><button class="btn ghost" data-action="site">Visit Developer Site</button></div></section>'; }
function wire(): void { document.querySelectorAll<HTMLElement>('[data-view]').forEach((button) => button.addEventListener('click', () => { view = button.dataset.view as View; notice = ''; render(); })); document.querySelector('[data-action=dismiss]')?.addEventListener('click', () => { notice = ''; render(); }); document.querySelector('[data-action=login]')?.addEventListener('click', () => void login()); document.querySelector('[data-action=logout]')?.addEventListener('click', () => void doLogout()); document.querySelector('[data-action=refresh]')?.addEventListener('click', () => void refreshPage()); document.querySelector('[data-action=leave]')?.addEventListener('click', () => void leaveSelected()); document.querySelector('[data-action=search]')?.addEventListener('click', () => void runSearch()); document.querySelector('[data-action=ask]')?.addEventListener('click', () => void ask()); document.querySelector('[data-action=clear-local]')?.addEventListener('click', () => void clearLocal()); document.querySelector('[data-action=cloud-sync]')?.addEventListener('click', () => void syncCloud()); document.querySelector('[data-action=delete-cloud]')?.addEventListener('click', () => void deleteCloud()); document.querySelector('[data-action=donate-custom]')?.addEventListener('click', () => void donateCustom()); document.querySelector('[data-action=donate-5]')?.addEventListener('click', () => void donateFixed(5)); document.querySelector('[data-action=donate-10]')?.addEventListener('click', () => void donateFixed(10)); document.querySelector('[data-action=donate-25]')?.addEventListener('click', () => void donateFixed(25)); document.querySelector('[data-action=donate-50]')?.addEventListener('click', () => void donateFixed(50)); document.querySelector('[data-action=site]')?.addEventListener('click', () => void openLink('siteUrl')); document.querySelector('#history-file')?.addEventListener('change', (event) => void importFile((event.target as HTMLInputElement).files?.[0])); document.querySelector('#memory-form')?.addEventListener('submit', (event) => void saveMemory(event)); document.querySelector('#schedule-form')?.addEventListener('submit', (event) => void saveSchedule(event)); document.querySelector('#rule-form')?.addEventListener('submit', (event) => void saveRule(event)); document.querySelectorAll<HTMLElement>('[data-delete-schedule]').forEach((button) => button.addEventListener('click', () => void removeSchedule(button.dataset.deleteSchedule!))); document.querySelectorAll<HTMLElement>('[data-delete-rule]').forEach((button) => button.addEventListener('click', () => void removeRule(button.dataset.deleteRule!))); document.querySelectorAll<HTMLElement>('[data-toggle-rule]').forEach((button) => button.addEventListener('click', () => void toggleRule(button.dataset.toggleRule!))); }
async function login(): Promise<void> { try { const origin = await apiOrigin(); const redirect = chrome.identity.getRedirectURL(); const result = await chrome.identity.launchWebAuthFlow({ url: origin + '/auth/discord/start?return_to=' + encodeURIComponent(redirect), interactive: true }); if (!result) throw new Error('Discord login did not complete'); const code = new URL(result).searchParams.get('code'); if (!code) throw new Error('Discord login did not complete'); await exchangeLoginCode(code); user = (await currentUser()).user; await refresh(); render(); } catch (error) { notice = 'Error: ' + errorText(error); render(); } }
async function doLogout(): Promise<void> { await logout(); user = undefined; guilds = []; schedules = []; rules = []; memories = []; render(); }
async function refreshPage(): Promise<void> { await refresh(); render(); }
async function leaveSelected(): Promise<void> { const selected = Array.from(document.querySelectorAll<HTMLInputElement>('[data-guild]:checked')).map((input) => guilds.find((guild) => guild.id === input.dataset.guild)).filter((guild): guild is Guild => Boolean(guild && !guild.owner)); if (!selected.length) { notice = 'Select at least one leaveable server.'; render(); return; } if (prompt('Type LEAVE to confirm leaving ' + selected.length + ' server(s).') !== 'LEAVE') return; for (const guild of selected) { try { await leaveOneGuild(guild); } catch (error) { notice = 'Error leaving ' + guild.name + ': ' + errorText(error); } } await refresh(); render(); }
async function importFile(file?: File): Promise<void> { if (!file) return; try { const parsed = await parseDiscordDataPackage(file); const count = await upsertMessages(parsed); messages = await searchMessages({}, 300); notice = 'Imported ' + count.toLocaleString() + ' messages locally.'; render(); } catch (error) { notice = 'Error: ' + errorText(error); render(); } }
async function clearLocal(): Promise<void> { if (confirm('Delete all local history from this browser?')) { await clearMessages(); messages = []; notice = 'Local history deleted.'; render(); } }
async function syncCloud(): Promise<void> { try { const local = await allMessages(100000); if (!local.length) throw new Error('Import local history first.'); const result = await api<{ imported: number }>('/messages/import', { method: 'POST', body: JSON.stringify({ messages: local }) }); notice = 'Synced ' + result.imported + ' messages to cloud.'; render(); } catch (error) { notice = 'Error: ' + errorText(error); render(); } }
async function runSearch(): Promise<void> { const query = document.querySelector<HTMLInputElement>('#message-query')?.value; const from = document.querySelector<HTMLInputElement>('#message-from')?.value; const to = document.querySelector<HTMLInputElement>('#message-to')?.value; messages = await searchMessages({ query, from, to }, 300); const target = document.querySelector('#message-results'); if (target) target.innerHTML = messageRows(messages); }
async function ask(): Promise<void> { const question = document.querySelector<HTMLInputElement>('#ai-question')?.value?.trim(); if (!question) return; try { const result: AiAnswer = await askAi(question, await searchMessages({ query: question }, 40)); const target = document.querySelector('#ai-answer'); if (target) target.innerHTML = '<div class="notice"><strong>' + esc(result.answer) + '</strong><br><small>' + result.citations.length + ' cited messages · ' + result.creditsRemaining + ' credits remaining</small></div>' + messageRows(result.citations); } catch (error) { notice = 'Error: ' + errorText(error); render(); } }
async function saveMemory(event: Event): Promise<void> { event.preventDefault(); const data = new FormData(event.target as HTMLFormElement); try { await createMemory({ title: data.get('title'), content: data.get('content'), tags: String(data.get('tags') || '').split(',').map((tag) => tag.trim()).filter(Boolean) }); memories = (await listMemories()).memories; render(); } catch (error) { notice = 'Error: ' + errorText(error); render(); } }
async function saveSchedule(event: Event): Promise<void> { event.preventDefault(); const data = new FormData(event.target as HTMLFormElement); try { const repeat = String(data.get('recurrence')); await createSchedule({ guildId: data.get('guildId'), channelId: data.get('channelId'), content: data.get('content'), runAt: new Date(String(data.get('runAt'))).toISOString(), ...(repeat !== 'none' ? { recurrence: repeat === 'daily' ? { kind: 'daily' } : { kind: 'interval', minutes: 15 } } : {}) }); schedules = (await listSchedules()).schedules; render(); } catch (error) { notice = 'Error: ' + errorText(error); render(); } }
async function saveRule(event: Event): Promise<void> { event.preventDefault(); const data = new FormData(event.target as HTMLFormElement); try { await createRule({ guildId: data.get('guildId'), channelId: data.get('channelId') || undefined, keyword: data.get('keyword'), match: data.get('match'), response: data.get('response') }); rules = (await listRules()).rules; render(); } catch (error) { notice = 'Error: ' + errorText(error); render(); } }
async function removeSchedule(id: string): Promise<void> { await deleteSchedule(id); schedules = (await listSchedules()).schedules; render(); }
async function removeRule(id: string): Promise<void> { await deleteRule(id); rules = (await listRules()).rules; render(); }
async function toggleRule(id: string): Promise<void> { const rule = rules.find((item) => item.id === id); if (rule) { await updateRule(id, { enabled: !rule.enabled }); rules = (await listRules()).rules; render(); } }
async function deleteCloud(): Promise<void> { if (confirm('Delete all cloud data?')) { await deleteCloudData(); memories = []; schedules = []; rules = []; notice = 'Cloud data deleted.'; render(); } }
async function donateCustom(): Promise<void> { const input = document.querySelector<HTMLInputElement>('#custom-amount'); const amount = parseFloat(input?.value || '0'); if (!amount || amount < 1 || amount > 500) { notice = 'Please enter an amount between $1 and $500'; render(); return; } const config = await getPublicConfig(); const url = config.donationUrl || 'https://stream-dream.shop'; chrome.tabs.create({ url: url + '?amount=' + amount }); }
async function donateFixed(amount: number): Promise<void> { const config = await getPublicConfig(); const url = config.donationUrl || 'https://stream-dream.shop'; chrome.tabs.create({ url: url + '?amount=' + amount }); }
async function openLink(key: 'donationUrl' | 'siteUrl'): Promise<void> { const config = await getPublicConfig(); if (config[key]) chrome.tabs.create({ url: config[key] }); else { notice = 'This link is not configured.'; render(); } }

boot().catch((error) => { notice = 'Error: ' + errorText(error); render(); });
